### ISSUE TITLE
Question about wrist coordinate system

### ISSUE THREAD

**Issue by BBBBBBob** [Improbable-AI/VisionProTeleop#12]
Thank you for such a cool project! I have a question about the wrist coordinate system. Does the coordinate system always follow this rule:
left:
x axis from wrist to middle
y axis from hand back to palm
z axis from index to little

right:
x axis from middle to wrist
y axis from palm to hand back
z axis from little to index？

Besides, where can I find the documentation about these coordinate systems?
Thank you!

**Comment by boreep** [comment]
Excuse me, I have the same doubt, now do you know the rules of the coordinate system?

**Comment by BBBBBBob** [comment]
Hi, you can check the axis convention in readme.
